### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/wallet-provider#2]
So one thing that has changed from the implementation in the app is `react-roastify` is no longer used to display different events to the users. I believe that this package should be opinionated about how connection info is displayed to a user. 

At the same time the wallet-provider should provide a way for some using this package to display those events to a user if they choose to.

## Whats needs

- Creating a set of global custom events that a user can subscribe to display to the user however they want.

**Comment by Da-Colon** [comment]
@adamgall

**Comment by adamgall** [comment]
sup

**Comment by Da-Colon** [comment]
So basically the conclusion on the other issue. is scrap logging. and ONLY do global events that a client can do with what they will

**Comment by adamgall** [comment]
kewl
